name: flutter_androssy_dialogs
description: "Customized alert dialog, editable dialog, loading dialog, message dialog, and some snacks"
version: 1.0.12
repository: https://github.com/Mohiuddin655-ORG/flutter_dialogs.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


