import 'package:flutter/material.dart';

import '../dialogs.dart';

Future<T?> showAndrossyDialog<T>({
  required BuildContext context,
  required AndrossyDialogBuilder builder,
  bool material = true,
  bool animated = true,
  bool barrierDismissible = true,
  double barrierBlurSigma = 5.0,
  Color? barrierColor,
  String? barrierLabel,
  Curve? curve,
  Curve? reverseCurve,
  Duration? duration,
  Duration? reverseDuration,
  Duration? displayDuration,
  bool useSafeArea = false,
  bool useRootNavigator = true,
  RouteSettings? routeSettings,
  Offset? anchorPoint,
  AndrossyDialogPosition position = AndrossyDialogPosition.center,
  AndrossyDialogTransitionBuilder? transitionBuilder,
  TraversalEdgeBehavior? traversalEdgeBehavior,

  // BOTTOM SHEET PROPERTY
  bool useModalBottomSheet = false,
  bool enableDrag = false,
  bool showDragHandle = false,
  bool isScrollControlled = false,
  AnimationStyle? sheetAnimationStyle,
  AnimationController? transitionAnimationController,
  double scrollControlDisabledMaxHeightRatio = 9.0 / 16.0,
  ShapeBorder? shape,
  double? elevation,
  Color? backgroundColor,
  BoxConstraints? constraints,
}) {
  return AndrossyDialog.show(
    context: context,
    builder: builder,
    anchorPoint: anchorPoint,
    animated: animated,
    backgroundColor: backgroundColor,
    barrierBlurSigma: barrierBlurSigma,
    barrierColor: barrierColor,
    barrierDismissible: barrierDismissible,
    barrierLabel: barrierLabel,
    curve: curve,
    constraints: constraints,
    duration: duration,
    displayDuration: displayDuration,
    elevation: elevation,
    enableDrag: enableDrag,
    isScrollControlled: isScrollControlled,
    material: material,
    position: position,
    reverseCurve: reverseCurve,
    reverseDuration: reverseDuration,
    routeSettings: routeSettings,
    shape: shape,
    scrollControlDisabledMaxHeightRatio: scrollControlDisabledMaxHeightRatio,
    sheetAnimationStyle: sheetAnimationStyle,
    showDragHandle: showDragHandle,
    transitionAnimationController: transitionAnimationController,
    transitionBuilder: transitionBuilder,
    traversalEdgeBehavior: traversalEdgeBehavior,
    useModalBottomSheet: useModalBottomSheet,
    useRootNavigator: useRootNavigator,
    useSafeArea: useSafeArea,
  );
}
